type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=disable&ApplicationName=featurebench&reWriteBatchedInserts=true
username: {{username}}
password: {{password}}
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
collect_pg_stat_statements: false
loaderthreads: 1
terminals: 1
yaml_version: v1.2
works:
    work:
        rate: unlimited
        serial: true

microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.bulkload.Goal2
    properties:
        setAutoCommit: true
        # Goal2 - 1 :: create table with PK -> create 1 index -> Load data (1 index)
        workload: create_1_index_then_load
        tableName: orders
        columns: 15
        rows: 3000000
        indexes: 1
        filePath: bulkload/goal1_2/orders.csv
        stringLength: 32
        create_index_before_load: true
        create_index_after_load: false
        recreateCsvIfExists: false
