type: POSTGRES
driver: org.postgresql.Driver
url: jdbc:postgresql://{{endpoint}}:5432/postgres?sslmode=require
username: {{username}}
password: {{password}}

batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
collect_pg_stat_statements: false
loaderthreads: 1
terminals: 1
yaml_version: v1.1
works:
    work:
        rate: unlimited
        serial: true
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.bulkload.Goal3
    properties:
        # Goal3 - 1 :: create table with 15 fields -> load data for 3M rows (only PK)
        workload: load_3Mrows
        tableName: orders
        columns: 15
        rows: 3000000
        filePath: bulkload/goal3/3m_orders.csv
        stringLength: 32
