type: POSTGRES
driver: org.postgresql.Driver
url: jdbc:postgresql://{{endpoint}}:5432/postgres?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true
username: {{username}}
password: {{password}}
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderThreads: 1
terminals: 1
collect_pg_stat_statements: true
yaml_version: v1.0

works:
    work:
        time_secs: 60
        active_terminals: 1
        rate: unlimited
        warmup: 30
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: false
        create:
            - DROP TABLE IF EXISTS employees_with_1_fk_1_to_1_cardinality;
            - DROP TABLE IF EXISTS projects_with_1_ref_1_to_1_cardinality;

            - DROP TABLE IF EXISTS employees_with_1_fk_1_to_10_cardinality;
            - DROP TABLE IF EXISTS projects_with_1_ref_1_to_10_cardinality;

            - DROP TABLE IF EXISTS employees_with_1_fk_1_to_100_cardinality;
            - DROP TABLE IF EXISTS projects_with_1_ref_1_to_100_cardinality;

            - DROP TABLE IF EXISTS employees_with_1_fk_1_to_1000_cardinality;
            - DROP TABLE IF EXISTS projects_with_1_ref_1_to_1000_cardinality;

            - create table projects_with_1_ref_1_to_1_cardinality(id int primary key, uid int unique not null, name varchar(20) not null, start_date date not null, end_date date, budget decimal(10,2));
            - create table employees_with_1_fk_1_to_1_cardinality(id int primary key,name varchar(20) not null, email varchar(100) not null, phone varchar(15), position varchar(10), salary decimal(10,2), project_id int not null);

            - create table projects_with_1_ref_1_to_10_cardinality(id int primary key, uid int unique not null, name varchar(20) not null, start_date date not null, end_date date, budget decimal(10,2));
            - create table employees_with_1_fk_1_to_10_cardinality(id int primary key,name varchar(20) not null, email varchar(100) not null, phone varchar(15), position varchar(10), salary decimal(10,2), project_id int not null);

            - create table projects_with_1_ref_1_to_100_cardinality(id int primary key, uid int unique not null, name varchar(20) not null, start_date date not null, end_date date, budget decimal(10,2));
            - create table employees_with_1_fk_1_to_100_cardinality(id int primary key,name varchar(20) not null, email varchar(100) not null, phone varchar(15), position varchar(10), salary decimal(10,2), project_id int not null);

            - create table projects_with_1_ref_1_to_1000_cardinality(id int primary key, uid int unique not null, name varchar(20) not null, start_date date not null, end_date date, budget decimal(10,2));
            - create table employees_with_1_fk_1_to_1000_cardinality(id int primary key,name varchar(20) not null, email varchar(100) not null, phone varchar(15), position varchar(10), salary decimal(10,2), project_id int not null);

            - CREATE INDEX project_uid_index_1_to_1_cardinality ON employees_with_1_fk_1_to_1_cardinality (project_id);
            - CREATE INDEX project_uid_index_1_to_10_cardinality ON employees_with_1_fk_1_to_10_cardinality (project_id);
            - CREATE INDEX project_uid_index_1_to_100_cardinality ON employees_with_1_fk_1_to_100_cardinality (project_id);
            - CREATE INDEX project_uid_index_1_to_1000_cardinality ON employees_with_1_fk_1_to_1000_cardinality (project_id);
            
        cleanup:
            - DROP TABLE IF EXISTS employees_with_1_fk_1_to_1_cardinality;
            - DROP TABLE IF EXISTS projects_with_1_ref_1_to_1_cardinality;

            - DROP TABLE IF EXISTS employees_with_1_fk_1_to_10_cardinality;
            - DROP TABLE IF EXISTS projects_with_1_ref_1_to_10_cardinality;

            - DROP TABLE IF EXISTS employees_with_1_fk_1_to_100_cardinality;
            - DROP TABLE IF EXISTS projects_with_1_ref_1_to_100_cardinality;

            - DROP TABLE IF EXISTS employees_with_1_fk_1_to_1000_cardinality;
            - DROP TABLE IF EXISTS projects_with_1_ref_1_to_1000_cardinality;
        loadRules:
            - table: projects_with_1_ref_1_to_1_cardinality
              rows: 100000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 100000]
                  - name: uid
                    util: PrimaryIntGen
                    params: [1, 100000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: start_date
                    util: RandomDateBtwYears
                    params: [2000, 2025]
                  - name: end_date
                    util: RandomDateBtwYears
                    params: [2000, 2025]
                  - name: budget
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]

            - table: employees_with_1_fk_1_to_1_cardinality
              rows: 100000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 100000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: email
                    util: RandomAString
                    params: [1, 100]
                  - name: phone
                    util: RandomNstring
                    params: [10, 15]
                  - name: position
                    util: RandomAString
                    params: [1, 10]
                  - name: salary
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]
                  - name: project_id
                    util: CyclicSeqIntGen
                    params: [1,100000]

            - table: projects_with_1_ref_1_to_10_cardinality
              rows: 100000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 100000]
                  - name: uid
                    util: PrimaryIntGen
                    params: [1, 100000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: start_date
                    util: RandomDateBtwYears
                    params: [2000, 2025]
                  - name: end_date
                    util: RandomDateBtwYears
                    params: [2000, 2025]
                  - name: budget
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]

            - table: employees_with_1_fk_1_to_10_cardinality
              rows: 1000000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 1000000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: email
                    util: RandomAString
                    params: [1, 100]
                  - name: phone
                    util: RandomNstring
                    params: [10, 15]
                  - name: position
                    util: RandomAString
                    params: [1, 10]
                  - name: salary
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]
                  - name: project_id
                    util: CyclicSeqIntGen
                    params: [1,100000]

            - table: projects_with_1_ref_1_to_100_cardinality
              rows: 100000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 100000]
                  - name: uid
                    util: PrimaryIntGen
                    params: [1, 100000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: start_date
                    util: RandomDateBtwYears
                    params: [2000, 2025]
                  - name: end_date
                    util: RandomDateBtwYears
                    params: [2000, 2025]
                  - name: budget
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]

            - table: employees_with_1_fk_1_to_100_cardinality
              rows: 10000000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 10000000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: email
                    util: RandomAString
                    params: [1, 100]
                  - name: phone
                    util: RandomNstring
                    params: [10, 15]
                  - name: position
                    util: RandomAString
                    params: [1, 10]
                  - name: salary
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]
                  - name: project_id
                    util: CyclicSeqIntGen
                    params: [1,100000]

            - table: projects_with_1_ref_1_to_1000_cardinality
              rows: 100000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 100000]
                  - name: uid
                    util: PrimaryIntGen
                    params: [1, 100000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: start_date
                    util: RandomDateBtwYears
                    params: [2000, 2025]
                  - name: end_date
                    util: RandomDateBtwYears
                    params: [2000, 2025]
                  - name: budget
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]

            - table: employees_with_1_fk_1_to_1000_cardinality
              rows: 100000000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 100000000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: email
                    util: RandomAString
                    params: [1, 100]
                  - name: phone
                    util: RandomNstring
                    params: [10, 15]
                  - name: position
                    util: RandomAString
                    params: [1, 10]
                  - name: salary
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]
                  - name: project_id
                    util: CyclicSeqIntGen
                    params: [1,100000]

        afterLoad:
            - ALTER TABLE employees_with_1_fk_1_to_1_cardinality add CONSTRAINT fk_project FOREIGN KEY (project_id) REFERENCES projects_with_1_ref_1_to_1_cardinality(uid) ON DELETE CASCADE ON UPDATE CASCADE;
            - ALTER TABLE employees_with_1_fk_1_to_10_cardinality add CONSTRAINT fk_project FOREIGN KEY (project_id) REFERENCES projects_with_1_ref_1_to_10_cardinality(uid) ON DELETE CASCADE ON UPDATE CASCADE;
            - ALTER TABLE employees_with_1_fk_1_to_100_cardinality add CONSTRAINT fk_project FOREIGN KEY (project_id) REFERENCES projects_with_1_ref_1_to_100_cardinality(uid) ON DELETE CASCADE ON UPDATE CASCADE;
            - ALTER TABLE employees_with_1_fk_1_to_1000_cardinality add CONSTRAINT fk_project FOREIGN KEY (project_id) REFERENCES projects_with_1_ref_1_to_1000_cardinality(uid) ON DELETE CASCADE ON UPDATE CASCADE;
            
        executeRules:

            - workload: FK_G4_1_update_1_to_1_cardinality
              run:
                  - name: FK_G4_1_update_1_to_1_cardinality
                    weight: 100
                    queries:
                        - query: update projects_with_1_ref_1_to_1_cardinality set uid=uid+100000 where id=?;
                          bindings:
                            - util: PrimaryIntGen
                              params: [1, 100000]

            - workload: FK_G4_2_delete_1_to_1_cardinality
              run:
                  - name: FK_G4_2_delete_1_to_1_cardinality
                    weight: 100
                    queries:
                        - query: delete from projects_with_1_ref_1_to_1_cardinality where id=?;
                          bindings:
                            - util: PrimaryIntGen
                              params: [1, 100000]

            - workload: FK_G4_3_update_1_to_10_cardinality
              run:
                  - name: FK_G4_3_update_1_to_10_cardinality
                    weight: 100
                    queries:
                        - query: update projects_with_1_ref_1_to_10_cardinality set uid=uid+100000 where id=?;
                          bindings:
                            - util: PrimaryIntGen
                              params: [1, 100000]

            - workload: FK_G4_4_delete_1_to_10_cardinality
              run:
                  - name: FK_G4_4_delete_1_to_10_cardinality
                    weight: 100
                    queries:
                        - query: delete from projects_with_1_ref_1_to_10_cardinality where id=?;
                          bindings:
                            - util: PrimaryIntGen
                              params: [1, 100000]

            - workload: FK_G4_5_update_1_to_100_cardinality
              run:
                  - name: FK_G4_5_update_1_to_100_cardinality
                    weight: 100
                    queries:
                        - query: update projects_with_1_ref_1_to_100_cardinality set uid=uid+100000 where id=?;
                          bindings:
                            - util: PrimaryIntGen
                              params: [1, 100000]

            - workload: FK_G4_6_delete_1_to_100_cardinality
              run:
                  - name: FK_G4_6_delete_1_to_100_cardinality
                    weight: 100
                    queries:
                        - query: delete from projects_with_1_ref_1_to_100_cardinality where id=?;
                          bindings:
                            - util: PrimaryIntGen
                              params: [1, 100000]

            - workload: FK_G4_7_update_1_to_1000_cardinality
              run:
                  - name: FK_G4_7_update_1_to_1000_cardinality
                    weight: 100
                    queries:
                        - query: update projects_with_1_ref_1_to_1000_cardinality set uid=uid+100000 where id=?;
                          bindings:
                            - util: PrimaryIntGen
                              params: [1, 100000]

            - workload: FK_G4_8_delete_1_to_1000_cardinality
              run:
                  - name: FK_G4_8_delete_1_to_1000_cardinality
                    weight: 100
                    queries:
                        - query: delete from projects_with_1_ref_1_to_1000_cardinality where id=?;
                          bindings:
                            - util: PrimaryIntGen
                              params: [1, 100000]