#GOAL12 HashJoin and Merge join tests
#TESTS:
# Filter condition returns 1 rows
# Filter condition returns 1000 rows .
type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true&load-balance=false
createdb: drop database if exists yb_colocated; create database yb_colocated with colocated=true
username: {{ username }}
password: {{ password }}
isolation: TRANSACTION_REPEATABLE_READ
batchsize: 128
terminals: 1
collect_pg_stat_statements: true
works:
    work:
        time_secs: 60
        active_terminals: 1
        rate: unlimited
        warmup: 30
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
            - DROP TABLE IF EXISTS pkey_rangescan_join_1;
            - DROP TABLE IF EXISTS pkey_rangescan_join_2;
            - CREATE TABLE pkey_rangescan_join_1(col_bigint_id_1 bigint, col_bigint_1 bigint, col_bigint_2 bigint, col_bigint_3 bigint, col_bigint_4 bigint, col_bigint_5 bigint, col_float2_1 float(2), col_float2_2 float(2), col_float5_1 float(5), col_float5_2 float(5), col_boolean_1 boolean, col_varchar10_1 varchar(10), col_varchar100_1 varchar(100), col_varchar100_2 varchar(100), col_varchar500_1 varchar(500), PRIMARY KEY(col_bigint_id_1 ASC, col_bigint_1 ASC));
            - CREATE TABLE pkey_rangescan_join_2(col_bigint_id_1 bigint, col_bigint_1 bigint, col_bigint_2 bigint, col_bigint_3 bigint, col_bigint_4 bigint, col_bigint_5 bigint, col_float2_1 float(2), col_float2_2 float(2), col_float5_1 float(5), col_float5_2 float(5), col_boolean_1 boolean, col_varchar10_1 varchar(10), col_varchar100_1 varchar(100), col_varchar100_2 varchar(100), col_varchar500_1 varchar(500), PRIMARY KEY(col_bigint_id_1 ASC, col_bigint_1 ASC));
        cleanup:
            - DROP TABLE IF EXISTS pkey_rangescan_join_1;
            - DROP TABLE IF EXISTS pkey_rangescan_join_2;
        loadRules:
            - table: pkey_rangescan_join_
              count: 2
              rows: 1000000
              columns:
                  - name: col_bigint_id_
                    count: 1
                    util: PrimaryIntGen
                    params: [1, 1000000]
                  - name: col_bigint_
                    count: 5
                    util: PrimaryIntGen
                    params: [1, 1000000]
                  - name: col_float2_
                    count: 2
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]
                  - name: col_float5_
                    count: 2
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 5]
                  - name: col_boolean_
                    count: 1
                    util: RandomBoolean
                  - name: col_varchar10_
                    count: 1
                    util: RandomAString
                    params: [10, 10]
                  - name: col_varchar100_
                    count: 2
                    util: RandomAString
                    params: [100, 100]
                  - name: col_varchar500_
                    count: 1
                    util: RandomAString
                    params: [500, 500]
        executeRules:
            - workload: scanG12_hash_join_fetch_1row
              run:
                  - name: hash_join_fetch_1row
                    weight: 100
                    queries:
                        - query: select pkey_rangescan_join_1.col_bigint_id_1 from pkey_rangescan_join_1 JOIN pkey_rangescan_join_2 on pkey_rangescan_join_1.col_bigint_2=pkey_rangescan_join_2.col_bigint_2 and pkey_rangescan_join_1.col_bigint_id_1 = 2 and pkey_rangescan_join_2.col_bigint_id_1 = 2 ;

            - workload: scanG12_hash_join_fetch_1000row
              run:
                  - name: hash_join_fetch_1000row
                    weight: 100
                    queries:
                        - query: select pkey_rangescan_join_1.col_bigint_id_1 from pkey_rangescan_join_1 JOIN pkey_rangescan_join_2 on pkey_rangescan_join_1.col_bigint_2=pkey_rangescan_join_2.col_bigint_2 and pkey_rangescan_join_1.col_bigint_id_1 < 1001 and pkey_rangescan_join_2.col_bigint_id_1 < 1001 ;

            - workload: scanG12_merge_join_fetch_1row
              run:
                  - name: merge_join_fetch_1row
                    weight: 100
                    queries:
                        - query: select pkey_rangescan_join_1.col_bigint_id_1 from pkey_rangescan_join_1 JOIN pkey_rangescan_join_2 on pkey_rangescan_join_1.col_bigint_id_1=pkey_rangescan_join_2.col_bigint_id_1 and pkey_rangescan_join_1.col_bigint_id_1 < 2  and pkey_rangescan_join_2.col_bigint_id_1 < 2;


            - workload: scanG12_merge_join_fetch_1000row
              run:
                  - name: merge_join_fetch_1000row
                    weight: 100
                    queries:
                        - query: select pkey_rangescan_join_1.col_bigint_id_1 from pkey_rangescan_join_1 JOIN pkey_rangescan_join_2 on pkey_rangescan_join_1.col_bigint_id_1=pkey_rangescan_join_2.col_bigint_id_1 and pkey_rangescan_join_1.col_bigint_id_1 < 1001 and pkey_rangescan_join_2.col_bigint_id_1 < 1001 ;