type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true
createdb: drop database if exists yb_colocated; create database yb_colocated with colocated=true
username: {{username}}
password: {{password}}

batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderThreads: 1
terminals: 1
collect_pg_stat_statements: true
use_dist_in_explain : true
analyze_on_all_tables: true
yaml_version: v1.0
works:
    work:
        time_secs: 60
        active_terminals: 1
        rate: unlimited
        warmup: 30
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: false
        create:
            - DROP TABLE IF EXISTS employees_with_int_fk;
            - DROP TABLE IF EXISTS employees_with_bigint_fk;
            - DROP TABLE IF EXISTS employees_with_varchar_fk;

            - DROP TABLE IF EXISTS projects_with_int_pk;
            - DROP TABLE IF EXISTS projects_with_bigint_pk;
            - DROP TABLE IF EXISTS projects_with_varchar_pk;

            - create table projects_with_int_pk(id int, name varchar(20) not null, start_date date not null, end_date date, budget decimal(10,2), primary key(id asc));
            - create table projects_with_bigint_pk(id bigint, name varchar(20) not null, start_date date not null, end_date date, budget decimal(10,2), primary key(id asc));
            - create table projects_with_varchar_pk(id varchar(6), name varchar(20) not null, start_date date not null, end_date date, budget decimal(10,2), primary key(id asc));

            - create table employees_with_int_fk(id int,name varchar(20) not null, email varchar(100) not null, phone varchar(15), position varchar(10), salary decimal(10,2), project_id int not null, primary key(id asc));
            - create table employees_with_bigint_fk(id int,name varchar(20) not null, email varchar(100) not null, phone varchar(15), position varchar(10), salary decimal(10,2), project_id bigint not null, primary key(id asc));
            - create table employees_with_varchar_fk(id int,name varchar(20) not null, email varchar(100) not null, phone varchar(15), position varchar(10), salary decimal(10,2), project_id varchar(6) not null, primary key(id asc));
        cleanup:
            - DROP TABLE IF EXISTS employees_with_int_fk;
            - DROP TABLE IF EXISTS employees_with_bigint_fk;
            - DROP TABLE IF EXISTS employees_with_varchar_fk;

            - DROP TABLE IF EXISTS projects_with_int_pk;
            - DROP TABLE IF EXISTS projects_with_bigint_pk;
            - DROP TABLE IF EXISTS projects_with_varchar_pk;
        loadRules:
            - table: projects_with_int_pk
              rows: 100000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 100000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: start_date
                    util: RandomDateBtwYears
                    params: [2000, 2025]
                  - name: end_date
                    util: RandomDateBtwYears
                    params: [2000, 2025]
                  - name: budget
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]

            - table: projects_with_bigint_pk
              rows: 100000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 100000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: start_date
                    util: RandomDateBtwYears
                    params: [2000, 2025]
                  - name: end_date
                    util: RandomDateBtwYears
                    params: [2000, 2025]
                  - name: budget
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]

            - table: projects_with_varchar_pk
              rows: 100000
              columns:
                  - name: id
                    util: PrimaryStringGen
                    params: [1, 6]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: start_date
                    util: RandomDateBtwYears
                    params: [2000, 2025]
                  - name: end_date
                    util: RandomDateBtwYears
                    params: [2000, 2025]
                  - name: budget
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]
              
            - table: employees_with_int_fk
              rows: 1000000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 1000000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: email
                    util: RandomAString
                    params: [1, 100]
                  - name: phone
                    util: RandomNstring
                    params: [10, 15]
                  - name: position
                    util: RandomAString
                    params: [1, 10]
                  - name: salary
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]
                  - name: project_id
                    util: RandomInt
                    params: [1,100000]
            
            - table: employees_with_bigint_fk
              rows: 1000000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 1000000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: email
                    util: RandomAString
                    params: [1, 100]
                  - name: phone
                    util: RandomNstring
                    params: [10, 15]
                  - name: position
                    util: RandomAString
                    params: [1, 10]
                  - name: salary
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]
                  - name: project_id
                    util: RandomInt
                    params: [1,100000]

            - table: employees_with_varchar_fk
              rows: 1000000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 1000000]
                  - name: name
                    util: RandomAString
                    params: [1, 20]
                  - name: email
                    util: RandomAString
                    params: [1, 20]
                  - name: phone
                    util: RandomNstring
                    params: [10, 15]
                  - name: position
                    util: RandomAString
                    params: [1, 10]
                  - name: salary
                    util: RandomNoWithDecimalPoints
                    params: [1, 1000000, 2]
                  - name: project_id
                    util: RandomPKString
                    params: [1,100000,6]

        afterLoad:
            - ALTER TABLE employees_with_int_fk add CONSTRAINT fk_project FOREIGN KEY (project_id) REFERENCES projects_with_int_pk(id);
            - ALTER TABLE employees_with_bigint_fk add CONSTRAINT fk_project FOREIGN KEY (project_id) REFERENCES projects_with_bigint_pk(id);
            - ALTER TABLE employees_with_varchar_fk add CONSTRAINT fk_project FOREIGN KEY (project_id) REFERENCES projects_with_varchar_pk(id);
            
        executeRules:

            - workload: FK_G3_1_varchar_insert
              run:
                  - name: FK_G3_1_varchar_insert
                    weight: 100
                    queries:
                        - query: insert into employees_with_varchar_fk values(?,?,?,?,?,?,?);
                          bindings:
                              - util: PrimaryIntGen
                                params: [1000001, 9000000]
                              - util: RandomAString
                                params: [1, 20]
                              - util: RandomAString
                                params: [1, 20]
                              - util: RandomNstring
                                params: [10, 15]
                              - util: RandomAString
                                params: [1, 10]
                              - util: RandomNoWithDecimalPoints
                                params: [1, 1000000, 2]
                              - util: RandomPKString
                                params: [1,100000,6]

            - workload: FK_G3_2_varchar_update
              run:
                  - name: FK_G3_2_varchar_update
                    weight: 100
                    queries:
                        - query: update employees_with_varchar_fk set project_id=? where id=?;
                          bindings:
                            - util: RandomPKString
                              params: [1,100000,6]
                            - util: PrimaryIntGen
                              params: [1,1000000]

            - workload: FK_G3_3_bigint_insert
              run:
                  - name: FK_G3_3_bigint_insert
                    weight: 100
                    queries:
                        - query: insert into employees_with_bigint_fk values(?,?,?,?,?,?,?);
                          bindings:
                              - util: PrimaryIntGen
                                params: [1000001, 9000000]
                              - util: RandomAString
                                params: [1, 20]
                              - util: RandomAString
                                params: [1, 100]
                              - util: RandomNstring
                                params: [10, 15]
                              - util: RandomAString
                                params: [1, 10]
                              - util: RandomNoWithDecimalPoints
                                params: [1, 1000000, 2]
                              - util: RandomInt
                                params: [1,100000]

            - workload: FK_G3_4_bigint_update
              run:
                  - name: FK_G3_4_bigint_update
                    weight: 100
                    queries:
                        - query: update employees_with_bigint_fk set project_id=? where id=?;
                          bindings:
                            - util: RandomInt
                              params: [1, 100000]
                            - util: PrimaryIntGen
                              params: [1, 1000000]
                              
            - workload: FK_G3_5_int_insert
              run:
                  - name: FK_G3_5_int_insert
                    weight: 100
                    queries:
                        - query: insert into employees_with_int_fk values(?,?,?,?,?,?,?);
                          bindings:
                              - util: PrimaryIntGen
                                params: [1000001, 9000000]
                              - util: RandomAString
                                params: [1, 20]
                              - util: RandomAString
                                params: [1, 100]
                              - util: RandomNstring
                                params: [10, 15]
                              - util: RandomAString
                                params: [1, 10]
                              - util: RandomNoWithDecimalPoints
                                params: [1, 1000000, 2]
                              - util: RandomInt
                                params: [1,100000]

            - workload: FK_G3_6_int_update
              run:
                  - name: FK_G3_6_int_update
                    weight: 100
                    queries:
                        - query: update employees_with_int_fk set project_id=? where id=?;
                          bindings:
                            - util: RandomInt
                              params: [1, 100000]
                            - util: PrimaryIntGen
                              params: [1, 1000000]