type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true
username: {{username}}
password: {{password}}
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderThreads: 1
terminals: 1
collect_pg_stat_statements: true
use_dist_in_explain : true
works:
    work:
        time_secs: 60
        rate: unlimited
        warmup: 30
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: false
        create:
            - DROP TABLE IF EXISTS pkeyBigint1M_1 CASCADE;
            - DROP TABLE IF EXISTS pkeyBigint1M_child_1 CASCADE;
            - CREATE TABLE pkeyBigint1M_1(col_bigint_card1_1 bigint, col_bigint_card2_1 bigint, col_bigint_card3_1 bigint, col_bigint_id_1 bigint, col_bigint_id_2 bigint, col_bigint_id_3 bigint, col_float2_1 float(2), col_float2_2 float(2), col_float5_1 float(5), col_float5_2 float(5), col_boolean_1 boolean, col_varchar10_id_1 varchar(10), col_varchar100_id_1 varchar(100), col_varchar100_id_2 varchar(100), col_varchar500_id_1 varchar(500), PRIMARY KEY(col_bigint_id_1));
            - CREATE INDEX ON pkeyBigint1M_1(col_bigint_card1_1);
            - CREATE INDEX ON pkeyBigint1M_1(col_bigint_card2_1 ASC) INCLUDE (col_bigint_id_2);
            - CREATE INDEX ON pkeyBigint1M_1(col_bigint_card3_1 DESC);
            - CREATE UNIQUE INDEX ON pkeyBigint1M_1(col_bigint_id_3);
            - CREATE TABLE pkeyBigint1M_child_1(col_bigint_id_1 bigint, col_bigint_id_2 bigint, col_bigint_id_3 bigint, col_varchar10_id_1 varchar(10), col_bigint_card1_1 bigint, col_bigint_card2_1 bigint, col_bigint_card3_1 bigint, PRIMARY KEY(col_bigint_id_1));
            - ALTER TABLE pkeyBigint1M_child_1 ADD CONSTRAINT pkeyBigint1M_child_id1_fk FOREIGN KEY (col_bigint_id_2) REFERENCES pkeyBigint1M_1 (col_bigint_id_1) ON UPDATE CASCADE;
            - ALTER TABLE pkeyBigint1M_child_1 ADD CONSTRAINT pkeyBigint1M_child_id2_fk FOREIGN KEY (col_bigint_id_3) REFERENCES pkeyBigint1M_1 (col_bigint_id_3) ON UPDATE CASCADE;
            - CREATE INDEX ON pkeyBigint1M_child_1(col_bigint_card1_1);

        cleanup:
            - DROP TABLE IF EXISTS pkeyBigint1M_1 CASCADE;
            - DROP TABLE IF EXISTS pkeyBigint1M_child_1 CASCADE;

        loadRules:
          - table: pkeyBigint1M_
            count: 1
            rows: 1000000
            columns:
                - name: col_bigint_card1_
                  count: 1
                  util: OneNumberFromArray
                  params: [ 1000000 ]
                - name: col_bigint_card2_
                  count: 1
                  util: RandomInt
                  params: [ 1000001,1001000 ]
                - name: col_bigint_card3_
                  count: 1
                  util: RandomInt
                  params: [ 1000001,1010000]
                - name: col_bigint_id_
                  count: 3
                  util: PrimaryIntGen
                  params: [ 1, 1000000 ]
                - name: col_float2_
                  count: 2
                  util: RandomNoWithDecimalPoints
                  params: [ 1, 1000000, 2 ]
                - name: col_float5_
                  count: 2
                  util: RandomNoWithDecimalPoints
                  params: [ 1, 1000000, 5 ]
                - name: col_boolean_
                  count: 1
                  util: RandomBoolean
                - name: col_varchar10_id_
                  count: 1
                  util: PrimaryStringGen
                  params: [1, 10]
                - name: col_varchar100_id_
                  count: 2
                  util: PrimaryStringGen
                  params: [1, 100]
                - name: col_varchar500_id_
                  count: 1
                  util: PrimaryStringGen
                  params: [1, 500]

          - table: pkeyBigint1M_child_
            count: 1
            rows: 1000000
            columns:
                - name: col_bigint_id_
                  count: 3
                  util: PrimaryIntGen
                  params: [ 1, 1000000 ]
                - name: col_varchar10_id_
                  count: 1
                  util: RandomAString
                  params: [10, 10]
                - name: col_bigint_card1_
                  count: 1
                  util: OneNumberFromArray
                  params: [ 1000000 ]
                - name: col_bigint_card2_
                  count: 1
                  util: RandomInt
                  params: [ 1000001,1001000 ]
                - name: col_bigint_card3_
                  count: 1
                  util: RandomInt
                  params: [ 1000001,1010000]

        executeRules:

            - workload: UG4_1_no_update_to_constraint_tbl1
              run:
                  - name: update_10_cols
                    weight: 100
                    queries:
                        - query: UPDATE pkeyBigint1M_1 SET col_bigint_id_1=?, col_bigint_id_2=?,col_bigint_id_3=?, col_bigint_card1_1=1000000, col_float2_1 = col_float2_1 + 1 where col_bigint_id_1 = ?
                          bindings:
                            - util: PrimaryIntGen
                              params: [ 1, 1000000 ]
                            - util: PrimaryIntGen
                              params: [ 1, 1000000 ]
                            - util: PrimaryIntGen
                              params: [ 1, 1000000 ]
                            - util: PrimaryIntGen
                              params: [ 1, 1000000 ]

            - workload: UG4_2_no_update_to_constraint_tbl2
              run:
                  - name: update_100_cols
                    weight: 100
                    queries:
                        - query: UPDATE pkeyBigint1M_child_1 SET col_bigint_id_1=?, col_bigint_id_2=?,col_bigint_id_3=?, col_bigint_card1_1=1000000, col_varchar10_id_1 = ? where col_bigint_id_1 = ?
                          bindings:
                            - util: PrimaryIntGen
                              params: [ 1, 1000000 ]
                            - util: PrimaryIntGen
                              params: [ 1, 1000000 ]
                            - util: PrimaryIntGen
                              params: [ 1, 1000000 ]
                            - util: RandomAString
                              params: [10, 10]
                            - util: PrimaryIntGen
                              params: [ 1, 1000000 ]

            - workload: UG4_3_no_update_to_constraint_on_conflict_tbl1
              run:
                  - name: update_10_cols
                    weight: 100
                    queries:
                        - query: INSERT INTO pkeyBigint1M_1 (col_bigint_card1_1,col_bigint_card2_1,col_bigint_card3_1,col_bigint_id_1,col_bigint_id_2,col_bigint_id_3,col_float2_1,col_float2_2,col_float5_1,col_float5_2,col_boolean_1,col_varchar10_id_1,col_varchar100_id_1,col_varchar100_id_2,col_varchar500_id_1) VALUES (1000000,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT (col_bigint_id_1) DO UPDATE SET col_varchar100_id_1 = 'updated_val' RETURNING *
                          bindings:
                            - util: RandomInt
                              params: [ 1000001,1001000 ]
                            - util: RandomInt
                              params: [ 1000001,1010000]
                            - util: PrimaryIntGen
                              params: [ 1, 1000000 ]
                            - util: PrimaryIntGen
                              params: [ 1, 1000000 ]
                            - util: PrimaryIntGen
                              params: [ 1, 1000000 ]
                            - util: RandomNoWithDecimalPoints
                              params: [ 1, 1000000, 2 ]
                            - util: RandomNoWithDecimalPoints
                              params: [ 1, 1000000, 2 ]
                            - util: RandomNoWithDecimalPoints
                              params: [ 1, 1000000, 5 ]
                            - util: RandomNoWithDecimalPoints
                              params: [ 1, 1000000, 5 ]
                            - util: RandomBoolean
                            - util: PrimaryStringGen
                              params: [1, 10]
                            - util: PrimaryStringGen
                              params: [1, 100]
                            - util: PrimaryStringGen
                              params: [1, 100]
                            - util: PrimaryStringGen
                              params: [1, 500]

            - workload: UG4_4_update_constraint_tbl1
              run:
                  - name: update_10_cols
                    weight: 100
                    queries:
                        - query: UPDATE pkeyBigint1M_1 SET col_bigint_id_1=?, col_bigint_id_2=?,col_bigint_id_3=?, col_bigint_card1_1=3000000, col_float2_1 = col_float2_1 + 1 where col_bigint_id_1 = ?
                          bindings:
                            - util: PrimaryIntGen
                              params: [ 1000001, 2000000 ]
                            - util: PrimaryIntGen
                              params: [ 1000001, 2000000 ]
                            - util: PrimaryIntGen
                              params: [ 1000001, 2000000 ]
                            - util: PrimaryIntGen
                              params: [ 1, 1000000 ]