type: POSTGRES
driver: org.postgresql.Driver
url: jdbc:postgresql://{{endpoint}}:5432/postgres?sslmode=require
username: {{username}}
password: {{password}}

batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
collect_pg_stat_statements: false
loaderthreads: 1
terminals: 1
yaml_version: v1.0
works:
    work:
        rate: unlimited
        serial: true

microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.bulkload.Goal1
    properties:
        # Goal 1 - 4 :: create table with PK -> create 10 index -> load data (10 index)
        workload: create10index_load
        tableName: orders
        columns: 15
        rows: 3000000
        indexes: 10
        filePath: orders.csv
        stringLength: 32
        recreateCsvIfExists: false
