type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true
createdb: drop database if exists yb_colocated; create database yb_colocated with colocated=true
username: {{username}}
password: {{password}}

batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 4
terminals: 24
collect_pg_stat_statements: true
use_dist_in_explain : true
yaml_version: v1.0
works:
    work:
        time_secs: 120
        rate: unlimited
        warmup: 30
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: false
        create:
            - drop sequence if exists seq1;
            - create sequence seq1;
            - drop table if exists seq_test_1;
            - create table seq_test_1 (id serial, col_int_1 int, col_int_2 int, col_int_3 int, col_varchar_1 varchar(20), col_varchar_2 varchar(20), col_varchar_3 varchar(20), col_date text, col_boolean boolean, primary key (id))
        cleanup:
            - drop sequence if exists seq1;
            - drop table if exists seq_test_1;
        loadRules:
            -   table: seq_test_
                count: 1
                rows: 100000
                columns:
                    -   name: col_int_
                        count: 3
                        util: RandomNumber
                        params:
                            - 1
                            - 1000000
                    -   name: col_varchar_
                        count: 3
                        util: RandomAString
                        params:
                            - 5
                            - 5
                    -   name: col_date
                        util: RandomAString
                        params:
                            - 5
                            - 5
                    -   name: col_boolean
                        util: RandomBoolean
        executeRules:
            -   workload: concurrent_nextval
                run:
                    -   name: concurrent_nextval
                        weight: 100
                        queries:
                            -   query: select nextval('seq1')

            -   workload: concurrent_insert_with_serial_pkey
                run:
                    -   name: concurrent_insert_with_serial_pkey
                        weight: 100
                        queries:
                            -   query: INSERT INTO seq_test_1 (col_int_1, col_int_2, col_int_3, col_varchar_1, col_varchar_2, col_varchar_3, col_date, col_boolean) values (?,?,?,?,?,?,?,?)
                                bindings:
                                    -   util: RandomNumber
                                        count: 3
                                        params: [ 1000001, 9000000 ]
                                    -   util: RandomAString
                                        count: 4
                                        params: [ 20, 20 ]
                                    -   util: RandomBoolean
