type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true&load-balance=false
createdb: drop database if exists yb_colocated; create database yb_colocated with colocated=true
username: {{username}}
password: {{password}}
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderThreads: 1
terminals: 1
collect_pg_stat_statements: true
use_dist_in_explain : true
yaml_version: v2.0
works:
    work:
        time_secs: 180
        rate: unlimited
        warmup: 60
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
            - DROP TABLE IF EXISTS accounts_1;
            - CREATE TABLE IF NOT EXISTS accounts_1(account_id_1 bigint, user_id_1 bigint, addr_1 varchar(50), bal_1 bigint,PRIMARY KEY(account_id_1));
            - CREATE UNIQUE INDEX user_accounts_1 ON accounts_1( user_id_1, account_id_1);
            - CREATE UNIQUE INDEX user_accounts_2 ON accounts_1( user_id_1, account_id_1, addr_1, bal_1);

        cleanup:
            - DROP TABLE IF EXISTS accounts_1;

        loadRules:
            -   table: accounts_
                count: 1
                rows: 6000000
                columns:
                    -   name: account_id_
                        count: 1
                        util: PrimaryIntGen
                        params: [ 1, 6000000 ]
                    -   name: user_id_
                        count: 1
                        util: PrimaryIntGen
                        params: [ 1, 6000000 ]
                    -   name: addr_
                        count: 1
                        util: OneStringFromArray
                        params: [ "addr for the client" ]
                    -   name: bal_
                        count: 1
                        util: PrimaryIntGen
                        params: [ 1, 6000000 ]

        executeRules:
            - workload: CW2_1_2column_condition_single_upsert
              run:
                  - name: statement1_insert
                    weight: 100
                    queries:
                        - query: INSERT INTO accounts_1(user_id_1,account_id_1,addr_1,bal_1) VALUES (?,?,?,?) ON CONFLICT (user_id_1, account_id_1) DO UPDATE SET (user_id_1,account_id_1,addr_1,bal_1)=(excluded.user_id_1,excluded.account_id_1,excluded.addr_1,excluded.bal_1)
                          bindings:
                              -   util: PrimaryIntGen
                                  params: [ 1, 1000000 ]
                              -   util: PrimaryIntGen
                                  params: [ 1, 1000000 ]
                              -   util: OneStringFromArray
                                  params: [ "Addr1 for the client" ]
                              -   util: PrimaryIntGen
                                  params: [ 1, 1000000]


            - workload: CW2_2_4column_condition_single_upsert
              run:
                  - name: statement1_insert
                    weight: 100
                    queries:
                        - query: INSERT INTO accounts_1(user_id_1,account_id_1,addr_1,bal_1) VALUES (?,?,?,?) ON CONFLICT (user_id_1, account_id_1, addr_1, bal_1) DO UPDATE SET (user_id_1,account_id_1,addr_1,bal_1)=(excluded.user_id_1,excluded.account_id_1,excluded.addr_1,excluded.bal_1)
                          bindings:
                              -   util: PrimaryIntGen
                                  params: [ 1000001, 2000000 ]
                              -   util: PrimaryIntGen
                                  params: [ 1000001, 2000000 ]
                              -   util: OneStringFromArray
                                  params: [ "Addr2 for the client" ]
                              -   util: PrimaryIntGen
                                  params: [ 1000001, 2000000]

            - workload: CW2_3_2column_condition_1024_upsert
              run:
                  - name: statement1_insert
                    weight: 100
                    queries:
                        - query: INSERT INTO accounts_1(user_id_1,account_id_1,addr_1,bal_1) VALUES (?,?,?,?) ON CONFLICT (user_id_1, account_id_1) DO UPDATE SET (user_id_1,account_id_1,addr_1,bal_1)=(excluded.user_id_1,excluded.account_id_1,excluded.addr_1,excluded.bal_1)
                          count: 1024
                          bindings:
                              -   util: PrimaryIntGen
                                  params: [ 2000001, 3000000 ]
                              -   util: PrimaryIntGen
                                  params: [ 2000001, 3000000 ]
                              -   util: OneStringFromArray
                                  params: [ "Addr3 for the client" ]
                              -   util: PrimaryIntGen
                                  params: [ 2000001, 3000000]

            - workload: CW2_4_2column_condition_2048_upsert
              run:
                  - name: statement1_insert
                    weight: 100
                    queries:
                        - query: INSERT INTO accounts_1(user_id_1,account_id_1,addr_1,bal_1) VALUES (?,?,?,?) ON CONFLICT (user_id_1, account_id_1) DO UPDATE SET (user_id_1,account_id_1,addr_1,bal_1)=(excluded.user_id_1,excluded.account_id_1,excluded.addr_1,excluded.bal_1)
                          count: 2048
                          bindings:
                              -   util: PrimaryIntGen
                                  params: [ 3000001, 4000000 ]
                              -   util: PrimaryIntGen
                                  params: [ 3000001, 4000000 ]
                              -   util: OneStringFromArray
                                  params: [ "Addr4 for the client" ]
                              -   util: PrimaryIntGen
                                  params: [ 3000001, 4000000]

            - workload: CW2_5_2column_condition_1_upsert_with_returning
              run:
                  - name: statement1_insert
                    weight: 100
                    queries:
                        - query: INSERT INTO accounts_1(user_id_1,account_id_1,addr_1,bal_1) VALUES (?,?,?,?) ON CONFLICT (user_id_1, account_id_1) DO UPDATE SET (user_id_1,account_id_1,addr_1,bal_1)=(excluded.user_id_1,excluded.account_id_1,excluded.addr_1,excluded.bal_1) RETURNING *
                          count: 10
                          bindings:
                              -   util: PrimaryIntGen
                                  params: [ 4000001, 5000000 ]
                              -   util: PrimaryIntGen
                                  params: [ 4000001, 5000000 ]
                              -   util: OneStringFromArray
                                  params: [ "Addr5 for the client" ]
                              -   util: PrimaryIntGen
                                  params: [ 4000001, 5000000]

            - workload: CW2_6_4column_condition_1_upsert_with_returning
              run:
                  - name: statement1_insert
                    weight: 100
                    queries:
                        - query: INSERT INTO accounts_1(user_id_1,account_id_1,addr_1,bal_1) VALUES (?,?,?,?) ON CONFLICT (user_id_1, account_id_1, addr_1, bal_1) DO UPDATE SET (user_id_1,account_id_1,addr_1,bal_1)=(excluded.user_id_1,excluded.account_id_1,excluded.addr_1,excluded.bal_1) RETURNING *
                          bindings:
                              -   util: PrimaryIntGen
                                  params: [ 5000001, 6000000 ]
                              -   util: PrimaryIntGen
                                  params: [ 5000001, 6000000 ]
                              -   util: OneStringFromArray
                                  params: [ "Addr6 for the client" ]
                              -   util: PrimaryIntGen
                                  params: [ 5000001, 6000000]

            - workload: CW2_7_2column_condition_10values_in_1upsert_with_returning
              run:
                  - name: statement1_insert
                    weight: 100
                    queries:
                        - query: INSERT INTO accounts_1(user_id_1,account_id_1,addr_1,bal_1) VALUES (?,?,?,?),(?,?,?,?),(?,?,?,?),(?,?,?,?),(?,?,?,?),(?,?,?,?),(?,?,?,?),(?,?,?,?),(?,?,?,?),(?,?,?,?) ON CONFLICT (user_id_1, account_id_1) DO UPDATE SET (user_id_1,account_id_1,addr_1,bal_1)=(excluded.user_id_1,excluded.account_id_1,excluded.addr_1,excluded.bal_1)
                          bindings:
                              -   util: CyclicSeqIntGen
                                  params: [ 1, 500000 ]
                              -   util: CyclicSeqIntGen
                                  params: [ 1, 500000 ]
                              -   util: OneStringFromArray
                                  params: [ "Addr7 for the client" ]
                              -   util: CyclicSeqIntGen
                                  params: [ 1, 500000]
                              -   util: CyclicSeqIntGen
                                  params: [ 500001, 1000000 ]
                              -   util: CyclicSeqIntGen
                                  params: [ 500001, 1000000 ]
                              -   util: OneStringFromArray
                                  params: [ "Addr8 for the client" ]
                              -   util: CyclicSeqIntGen
                                  params: [ 500001, 1000000 ]
                              -   util: CyclicSeqIntGen
                                  params: [ 2000001, 2500000 ]
                              -   util: CyclicSeqIntGen
                                  params: [ 2000001, 2500000 ]
                              -   util: OneStringFromArray
                                  params: [ "Addr9 for the client" ]
                              -   util: CyclicSeqIntGen
                                  params: [ 2000001, 2500000 ]
                              -   util: CyclicSeqIntGen
                                  params: [ 2500001, 3000000 ]
                              -   util: CyclicSeqIntGen
                                  params: [ 2500001, 3000000 ]
                              -   util: OneStringFromArray
                                  params: [ "Addr10 for the client" ]
                              -   util: CyclicSeqIntGen
                                  params: [ 2500001, 3000000 ]
                              -   util: CyclicSeqIntGen
                                  params: [ 3000001, 3500000 ]
                              -   util: CyclicSeqIntGen
                                  params: [ 3000001, 3500000 ]
                              -   util: OneStringFromArray
                                  params: [ "Addr11 for the client" ]
                              -   util: CyclicSeqIntGen
                                  params: [ 3000001, 3500000 ]
                              -   util: CyclicSeqIntGen
                                  params: [ 3500001, 4000000 ]
                              -   util: CyclicSeqIntGen
                                  params: [ 3500001, 4000000 ]
                              -   util: OneStringFromArray
                                  params: [ "Addr12 for the client" ]
                              -   util: CyclicSeqIntGen
                                  params: [ 3500001, 4000000 ]
                              -   util: CyclicSeqIntGen
                                  params: [ 4000001, 4500000 ]
                              -   util: CyclicSeqIntGen
                                  params: [ 4000001, 4500000 ]
                              -   util: OneStringFromArray
                                  params: [ "Addr13 for the client" ]
                              -   util: CyclicSeqIntGen
                                  params: [ 4000001, 4500000 ]
                              -   util: CyclicSeqIntGen
                                  params: [ 4500001, 5000000 ]
                              -   util: CyclicSeqIntGen
                                  params: [ 4500001, 5000000 ]
                              -   util: OneStringFromArray
                                  params: [ "Addr14 for the client" ]
                              -   util: CyclicSeqIntGen
                                  params: [ 4500001, 5000000 ]
                              -   util: CyclicSeqIntGen
                                  params: [ 4250001, 4750000 ]
                              -   util: CyclicSeqIntGen
                                  params: [ 4250001, 4750000 ]
                              -   util: OneStringFromArray
                                  params: [ "Addr15 for the client" ]
                              -   util: CyclicSeqIntGen
                                  params: [ 4250001, 4750000 ]
                              -   util: CyclicSeqIntGen
                                  params: [ 3250001, 3750000 ]
                              -   util: CyclicSeqIntGen
                                  params: [ 3250001, 3750000 ]
                              -   util: OneStringFromArray
                                  params: [ "Addr16 for the client" ]
                              -   util: CyclicSeqIntGen
                                  params: [ 3250001, 3750000 ]

            - workload: CW2_8_2column_condition_1_upsert_with_returning
              run:
                  - name: statement1_insert
                    weight: 100
                    queries:
                        - query: INSERT INTO accounts_1(user_id_1,account_id_1,addr_1,bal_1) VALUES (?,?,?,?) ON CONFLICT (user_id_1, account_id_1) DO UPDATE SET bal_1=accounts_1.bal_1+1 RETURNING *
                          bindings:
                              -   util: PrimaryIntGen
                                  params: [ 6000001, 7000000 ]
                              -   util: PrimaryIntGen
                                  params: [ 6000001, 7000000 ]
                              -   util: OneStringFromArray
                                  params: [ "Addr17 for the client" ]
                              -   util: PrimaryIntGen
                                  params: [ 6000001, 7000000]

            - workload: CW2_9_2column_condition_10_upsert_with_returning
              run:
                  - name: statement1_insert
                    weight: 100
                    queries:
                        - query: INSERT INTO accounts_1(user_id_1,account_id_1,addr_1,bal_1) VALUES (?,?,?,?) ON CONFLICT (user_id_1, account_id_1) DO UPDATE SET bal_1=accounts_1.bal_1+1 RETURNING *
                          count: 10
                          bindings:
                              -   util: PrimaryIntGen
                                  params: [ 7000001, 8000000 ]
                              -   util: PrimaryIntGen
                                  params: [ 7000001, 8000000 ]
                              -   util: OneStringFromArray
                                  params: [ "Addr18 for the client" ]
                              -   util: PrimaryIntGen
                                  params: [ 7000001, 8000000]
