type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=disable&ApplicationName=featurebench&reWriteBatchedInserts=true
username: {{username}}
password: {{password}}
createdb: drop database if exists yb_colocated; create database yb_colocated with colocated=true
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
collect_pg_stat_statements: false
loaderthreads: 1
terminals: 1
yaml_version: v1.2
works:
    work:
        rate: unlimited
        serial: true
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.bulkload.Goal4
    properties:
        setAutoCommit: true
        # Goal4 - 2 :: create table with 20 fields, 3M rows -> load data (only PK)
        workload: create_20fields_table_then_load
        tableName: orders
        columns: 20
        rows: 3000000
        filePath: bulkload/goal4/20col_orders.csv
        stringLength: 32