type: POSTGRES
driver: org.postgresql.Driver
url: jdbc:postgresql://{{endpoint}}:5432/postgres?sslmode=require
username: {{username}}
password: {{password}}

batchsize: 128
isolation: TRANSACTION_READ_COMMITTED
loaderthreads: 1
terminals: 24
collect_pg_stat_statements: true
yaml_version: v1.0
works:
    work:
        time_secs: 120
        rate: unlimited
        warmup: 30
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: false
        create:
            - drop table if exists update_test_table1;
            - create table update_test_table1 (id bigint, col_int_1 int, col_int_2 int, col_int_3 int, col_int_4 int, col_int_5 int, col_int_6 int, col_int_7 int, col_int_8 int, col_int_9 int, col_int_10 int, col_varchar_1 varchar(20), col_varchar_2 varchar(20), col_varchar_3 varchar(20), col_date text, col_boolean boolean, primary key (id))
        cleanup:
            - drop table if exists update_test_table1;
        loadRules:
            - table: update_test_table1
              rows: 1000000
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params: [1, 1000000]
                  - name: col_int_
                    count: 10
                    util: RandomNumber
                    params: [1, 1000000]
                  - name: col_varchar_
                    count: 3
                    util: RandomAString
                    params: [20, 20]
                  - name: col_date
                    util: RandomAString
                    params: [20, 20]
                  - name: col_boolean
                    util: RandomBoolean
        executeRules:
            - workload: select_update_key_from_multiple_threads_with_weights_100
              run:
                  - name: update_same_key
                    weight: 100
                    queries:
                        - query: select * from update_test_table1 where id = 1 for update
                        - query: select pg_sleep(0.001)
                        - query: update update_test_table1 set col_varchar_3 = ? where id = 1
                          bindings:
                              - util: RandomAString
                                params: [20, 20]