type: POSTGRES
driver: org.postgresql.Driver
url: jdbc:postgresql://{{endpoint}}:5432/postgres?sslmode=require
username: {{username}}
password: {{password}}
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 1
terminals: 24
collect_pg_stat_statements: true
use_dist_in_explain : true
yaml_version: v1.0
works:
    work:
        time_secs: 300
        rate: unlimited
        warmup: 60
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
            - DROP TABLE IF EXISTS users_1;
            - DROP TABLE IF EXISTS accounts_1;
            - DROP TABLE IF EXISTS audit_table_1;
            - CREATE TABLE IF NOT EXISTS users_1(user_id_1 bigint, user_name_1 varchar(10), addr_1 varchar(50), bal_1 float(2), PRIMARY KEY(user_id_1));
            - CREATE TABLE IF NOT EXISTS accounts_1(account_id_1 bigint, user_id_1 bigint, addr_1 varchar(50), bal_1 float(2), PRIMARY KEY(account_id_1));
            - CREATE UNIQUE INDEX user_accounts ON accounts_1( user_id_1, account_id_1);
            - CREATE TABLE IF NOT EXISTS audit_table_1(account_id_1 bigint, event_id_1 date, user_id_1 bigint, delta_1 float(2), PRIMARY KEY(account_id_1, event_id_1));

        cleanup:
            - DROP TABLE IF EXISTS users_1;
            - DROP TABLE IF EXISTS accounts_1;
            - DROP TABLE IF EXISTS audit_table_1;

        loadRules:
            -   table: users_
                count: 1
                rows: 1000000
                columns:
                    -   name: user_id_
                        count: 1
                        util: PrimaryIntGen
                        params: [ 1, 1000000 ]
                    -   name: user_name_
                        count: 1
                        util: PrimaryStringGen
                        params: [ 1, 10 ]
                    -   name: addr_
                        count: 1
                        util: PrimaryStringGen
                        params: [ 1, 50 ]
                    -   name: bal_
                        count: 1
                        util: RandomNoWithDecimalPoints
                        params: [ 1, 1000000, 2 ]

            -   table: accounts_
                count: 1
                rows: 1000000
                columns:
                    -   name: account_id_
                        count: 1
                        util: PrimaryIntGen
                        params: [ 1, 1000000 ]
                    -   name: user_id_
                        count: 1
                        util: PrimaryIntGen
                        params: [ 1, 1000000 ]
                    -   name: addr_
                        count: 1
                        util: PrimaryStringGen
                        params: [ 1, 50 ]
                    -   name: bal_
                        count: 1
                        util: RandomNoWithDecimalPoints
                        params: [ 1, 1000000, 2 ]

            -   table: audit_table_
                count: 1
                rows: 1000000
                columns:
                    -   name: account_id_
                        count: 1
                        util: PrimaryIntGen
                        params: [ 1, 1000000 ]
                    -   name: event_id_
                        count: 1
                        util: PrimaryDateGen
                        params: [2000000]
                    -   name: user_id_
                        count: 1
                        util: PrimaryIntGen
                        params: [ 1, 1000000 ]
                    -   name: delta_
                        count: 1
                        util: RandomNoWithDecimalPoints
                        params: [ 1, 1000000, 2 ]


        executeRules:
            - workload: MG2_1_multi_statement_transaction_run1
              customTags: customer=10,schematype=regular,partition=hash,pkey=composite,cardinality=single,projection=all,filtercount=one,filteron=hashpkey,filtertype=pointselect,queryshape=scan
              run:
                  - name: statement1_insert
                    weight: 100
                    queries:
                        - query: INSERT INTO audit_table_1(account_id_1, event_id_1, user_id_1, delta_1) VALUES(?,?,?,?)
                          bindings:
                              -   util: PrimaryIntGen
                                  params: [ 2000000, 100000000 ]
                              -   util: PrimaryDateGen
                                  params: [ 100000000 ]
                              -   util: PrimaryIntGen
                                  params: [ 2000000, 100000000 ]
                              -   util: RandomNoWithDecimalPoints
                                  params: [ 1, 1000000, 2 ]
                        - query: UPDATE accounts_1 SET bal_1 = ? WHERE account_id_1 = ? and user_id_1 = ?
                          bindings:
                              -   util: RandomNoWithDecimalPoints
                                  params: [ 1000000, 10000000, 2 ]
                              -   util: PrimaryIntGen
                                  params: [ 1, 1000000 ]
                              -   util: PrimaryIntGen
                                  params: [ 1, 1000000 ]
                        - query: SELECT bal_1 FROM accounts_1 WHERE account_id_1 = ?
                          bindings:
                              -   util: PrimaryIntGen
                                  params: [ 1, 1000000 ]
                        - query: UPDATE users_1 SET bal_1 = bal_1 + ? WHERE user_id_1 = ?
                          bindings:
                              -   util: RandomInt
                                  params: [ 1, 100 ]
                              -   util: PrimaryIntGen
                                  params: [ 1, 1000000 ]