type: POSTGRES
driver: org.postgresql.Driver
url: jdbc:postgresql://{{endpoint}}:5432/postgres?sslmode=require
username: {{username}}
password: {{password}}
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 1
terminals: 1
collect_pg_stat_statements: true
yaml_version: v1.0
works:
    work:
        time_secs: 180
        active_terminals: 1
        rate: unlimited
        warmup: 60
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
          - DROP TABLE IF EXISTS iNDG12_U_pkeyBigint1M_1;
          - CREATE TABLE iNDG12_U_pkeyBigint1M_1(col_bigint_card1_1 bigint, col_bigint_card2_1 bigint, col_bigint_card3_1 bigint, col_bigint_id_1 bigint, col_bigint_id_2 bigint, col_bigint_id_3 bigint, col_float2_1 float(2), col_float2_2 float(2), col_float5_1 float(5), col_float5_2 float(5), col_boolean_1 boolean, col_varchar10_id_1 varchar(10), col_varchar100_id_1 varchar(100), col_varchar100_id_2 varchar(100), col_varchar500_id_1 varchar(500), PRIMARY KEY(col_bigint_id_1));
          - CREATE INDEX ON iNDG12_U_pkeyBigint1M_1(col_bigint_card1_1);
          - CREATE INDEX ON iNDG12_U_pkeyBigint1M_1(col_bigint_card2_1 ASC);
          - CREATE INDEX ON iNDG12_U_pkeyBigint1M_1(col_bigint_card3_1 DESC);

        cleanup:
            - DROP TABLE IF EXISTS iNDG12_U_pkeyBigint1M_1;

        loadRules:
              - table: iNDG12_U_pkeyBigint1M_
                count: 1
                rows: 1000000
                columns:
                    - name: col_bigint_card1_
                      count: 1
                      util: RandomInt
                      params: [ 1000001, 1001000 ]
                    - name: col_bigint_card2_
                      count: 1
                      util: RandomInt
                      params: [ 1000001, 1001000 ]
                    - name: col_bigint_card3_
                      count: 1
                      util: RandomInt
                      params: [ 1000001, 1001000 ]
                    - name: col_bigint_id_
                      count: 3
                      util: RandomUniqueIntGen
                      params: [ 1, 1000000 ]
                    - name: col_float2_
                      count: 2
                      util: RandomNoWithDecimalPoints
                      params: [ 1, 1000000, 2 ]
                    - name: col_float5_
                      count: 2
                      util: RandomNoWithDecimalPoints
                      params: [ 1, 1000000, 5 ]
                    - name: col_boolean_
                      count: 1
                      util: RandomBoolean
                    - name: col_varchar10_id_
                      count: 1
                      util: PrimaryStringGen
                      params: [1, 10]
                    - name: col_varchar100_id_
                      count: 2
                      util: PrimaryStringGen
                      params: [1, 100]
                    - name: col_varchar500_id_
                      count: 1
                      util: PrimaryStringGen
                      params: [1, 500]


        executeRules:

            - workload: INDG12_1_index_scan_hash_skey_point_select
              customTags: schematype=regular,partition=hash,pkey=single,cardinality=multiple,projection=all,filtercount=one,filteron=hashskey,filtertype=pointselect
              run:
                  - name: hashtbl_index_scan_using_sec_index
                    weight: 100
                    queries:
                        - query: select * from iNDG12_U_pkeyBigint1M_1 where col_bigint_card1_1 IN (1000080,1000100,1000099,1000580,1000880);

            - workload: INDG12_2_index_scan_range_skey_point_select
              customTags: schematype=regular,partition=hash,pkey=single,cardinality=multiple,projection=all,filtercount=one,filteron=rangeskey,filtertype=pointselect
              run:
                  - name: hashtbl_index_scan_using_sec_index
                    weight: 100
                    queries:
                        - query: select * from iNDG12_U_pkeyBigint1M_1 where col_bigint_card2_1 IN (1000080,1000100,1000099,1000580,1000880);

            - workload: INDG12_3_index_scan_range_skey_desc_point_select
              customTags: schematype=regular,partition=hash,pkey=single,cardinality=multiple,projection=all,filtercount=one,filteron=rangeskey,filtertype=pointselect
              run:
                  - name: hashtbl_index_scan_using_sec_index
                    weight: 100
                    queries:
                        - query: select * from iNDG12_U_pkeyBigint1M_1 where col_bigint_card3_1 IN (1000080,1000100,1000099,1000580,1000880);
