type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://{{endpoint}}:5433/yugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true&load-balance=false
username: {{username}}
password: {{password}}
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 1
terminals: 1
collect_pg_stat_statements: true
use_dist_in_explain : true
yaml_version: v1.0
works:
    work:
        time_secs: 600
        active_terminals: 1
        rate: unlimited
        warmup: 60
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
            - DROP TABLE IF EXISTS INDG13_U_rangetbl_1;
            - CREATE TABLE INDG13_U_rangetbl_1(col_bigint_id_1 bigint, col_bigint_id_2 bigint, col_bigint_id_3 bigint, col_bigint_id_4 bigint, col_bigint_1 bigint, col_bigint_2 bigint, col_float2_1 float(2), col_float2_2 float(2), col_float5_1 float(5), col_float5_2 float(5), col_boolean_1 boolean, col_varchar10_id_1 varchar(10), col_varchar100_id_1 varchar(100), col_varchar100_id_2 varchar(100), col_varchar500_id_1 varchar(500), PRIMARY KEY(col_bigint_id_1 ASC));
            - CREATE INDEX ON INDG13_U_rangetbl_1(col_bigint_id_2 ASC);

        cleanup:
            - DROP TABLE IF EXISTS INDG13_U_rangetbl_1;

        loadRules:
              - table: INDG13_U_rangetbl_
                count: 1
                rows: 1000000
                columns:
                    - name: col_bigint_id_
                      count: 4
                      util: RandomUniqueIntGen
                      params: [ 1, 1000000 ]
                    - name: col_bigint_
                      count: 2
                      util: RandomNumber
                      params: [ 1, 1000000 ]
                    - name: col_float2_
                      count: 2
                      util: RandomNoWithDecimalPoints
                      params: [ 1, 1000000, 2 ]
                    - name: col_float5_
                      count: 2
                      util: RandomNoWithDecimalPoints
                      params: [ 1, 1000000, 5 ]
                    - name: col_boolean_
                      count: 1
                      util: RandomBoolean
                    - name: col_varchar10_id_
                      count: 1
                      util: PrimaryStringGen
                      params: [1, 10]
                    - name: col_varchar100_id_
                      count: 2
                      util: PrimaryStringGen
                      params: [1, 100]
                    - name: col_varchar500_id_
                      count: 1
                      util: PrimaryStringGen
                      params: [1, 500]

        executeRules:
            - workload: INDG13_1_indexscan_using_pkey
              customTags: schematype=regular,partition=range,pkey=asc,cardinality=single,projection=indexed,queryshape=join,joinon=rangepkey
              run:
                  - name: join_on_pk_of_range_tbl
                    weight: 100
                    queries:
                        - query: select col_bigint_id_1 from INDG13_U_rangetbl_1 where col_bigint_id_1>0

            -   workload: INDG13_2_indexonlyscan_using_skey
                customTags: schematype=regular,partition=range,pkey=asc,cardinality=single,projection=indexed,queryshape=join,joinon=rangepkey
                run:
                    -   name: join_on_pk_of_range_tbl
                        weight: 100
                        queries:
                            -   query: select col_bigint_id_2 from INDG13_U_rangetbl_1 where col_bigint_id_2>0

            -   workload: INDG13_3_indexscan_using_skey
                customTags: schematype=regular,partition=range,pkey=asc,cardinality=single,projection=indexed,queryshape=join,joinon=rangepkey
                run:
                    -   name: join_on_pk_of_range_tbl
                        weight: 100
                        queries:
                            -   query: select col_bigint_id_1 from INDG13_U_rangetbl_1 where col_bigint_id_2>0
