type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://localhost:5433/yugabyte?sslmode=disable&ApplicationName=featurebench&reWriteBatchedInserts=true
username: yugabyte
password: null
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 1
collect_pg_stat_statements: true
terminals: 1
works:
    work:
        time_secs: 5
        active_terminals: 1
        rate: 1000
        warmup: 0
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit: true
        create:
            - DROP TABLE IF EXISTS demo_batch_insert;
            - CREATE TABLE demo_batch_insert (id INT, col1 TEXT, col2 TEXT, col3 TEXT, primary key (id ASC)) ;
        loadRules:
            - table: demo_batch_insert
              rows: 10
              columns:
                  - name: id
                    util: PrimaryIntGen
                    params:
                        - 1
                        - 10
                  - name: col
                    count: 3
                    util: RandomStringNumeric
                    params:
                        - 128
        executeRules:
            - workload: Insert
              run:
                  - name: BatchInsert
                    weight: 100
                    queries:
                        - query: INSERT INTO demo_batch_insert VALUES [(?,?,?,?)][pattern_count]
                          pattern_count: 5
                          bindings:
                              - util: PrimaryIntGen
                                params:
                                    - 100
                                    - 100000
                              - util: RandomAString
                                count: 3
                                params:
                                    - 5
                                    - 5
